version: '3.2'
services:
    cas:
        command: sh -c "SCONE_HEAP=2G cas -c /etc/cas/cas.toml"
        environment:
         - SCONE_LOG=7
         - SCONE_MODE=sim
        image: sconecuratedimages/services:cas.trust.group-out-of-date-scone4.2.1
        devices:
            - "/dev/isgx"
        # ports:
        #     - target: 8081
        #       published: 8081
        #       protocol: tcp
        #       mode: host
        #     - target: 18765
        #       published: 18765
        #       protocol: tcp
        #       mode: host
    mongodb:
      build:
        dockerfile: docker/mongodb/Dockerfile
        context: .
      tty: true
      devices:
          - "/dev/isgx"
      environment: 
        - SCONE_LOG=7
        - SCONE_MODE=hw
        - SCONE_CAS_ADDR=cas
        - SCONE_LAS_ADDR=las
        - SCONE_ALLOW_DLOPEN=2
      # ports:
      #     - target: 27017
      #       published: 27017
      #       protocol: tcp
      #       mode: host
    demo-client:
      command: sh
      tty: true
      build :
        dockerfile: demo-client/Dockerfile
        context: .
      devices:
          - "/dev/isgx"
      environment: 
        - SCONE_LOG=7
        - SCONE_MODE=hw
        - SCONE_CAS_ADDR=cas
        - SCONE_LAS_ADDR=las
      # expose: 
      #   - "27017"
    vault:
        command: sh
        image : vault_alpine_ykhedar
        tty: true
        devices:
            - "/dev/isgx"
        environment: 
          - SCONE_LOG=7
          - SCONE_MODE=hw
          - SCONE_CAS_ADDR=cas
          - SCONE_LAS_ADDR=las
          - VAULT_ADDR=http://127.0.0.1:8200
    consul:
        command: consul agent -dev -ui -client 0.0.0.0
        build: docker/vault_dockerfile/consul/
        #expose:
        #  - "8500"
    las:
        image: sconecuratedimages/services:las-scone4.2.1
        environment:
          - SCONE_LOG=7
          - SCONE_MODE=hw
        devices:
          - "/dev/isgx"
            #ports:
            #- target: 18766
            #published: 18766
            #protocol: tcp
            #mode: host