version: '3.2'
services:
    cas:
        command: sh -c "SCONE_HEAP=1G cas -c /etc/cas/cas.toml"
        environment:
         - SCONE_LOG=7
         - SCONE_MODE=hw
        image: sconecuratedimages/services:cas
        devices:
            - "/dev/gsgx"
        ports:
          - target: 8081
            published: 8081
            protocol: tcp
            mode: host
          - target: 18765
            published: 18765
            protocol: tcp
            mode: host
    vault:
        command: sh
        build : .
        tty: true
        devices:
            - "/dev/gsgx"
        environment: 
          - SCONE_LOG=7
          - SCONE_MODE=hw
          - SCONE_CAS_ADDR=cas
          - SCONE_LAS_ADDR=las
    consul:
        command: consul agent -dev -ui -client 0.0.0.0
        build: docker/vault_dockerfile/vault_scone_ubuntu/consul/
        expose:
          - "8500"
    las:
        image: sconecuratedimages/services:las
        environment:
          - SCONE_LOG=7
          - SCONE_MODE=hw
        devices:
          - "/dev/gsgx"
        ports:
          - target: 18766
            published: 18766
            protocol: tcp
            mode: host
        
