version: '3.2'
services:
    cas:
        command: sh -c "SCONE_HEAP=1G cas -c /etc/cas/cas.toml"
        environment:
         - SCONE_LOG=7
         - SCONE_MODE=hw
        image: sconecuratedimages/services:cas
        devices:
            - "/dev/isgx"
        ports:
          - target: 8081
            published: 8081
            protocol: tcp
            mode: host
          - target: 18765
            published: 18765
            protocol: tcp
            mode: host
    vault:
        command: sh
        build: .
        tty: true
        devices:
            - "/dev/isgx"
        environment: 
          - SCONE_LOG=7
          - SCONE_MODE=hw
          - SCONE_CAS_ADDR=cas
          - SCONE_LAS_ADDR=las
    consul:
        command: consul agent -dev
        image: consul
        ports:
          - target: 8500
            published: 8500
            protocol: tcp
            mode: host
          - target: 80
            published: 80
            protocol: tcp
            mode: host
    las:
        image: sconecuratedimages/services:las
        environment:
          - SCONE_LOG=7
          - SCONE_MODE=hw
        devices:
          - "/dev/isgx"
        ports:
          - target: 18766
            published: 18766
            protocol: tcp
            mode: host
        