version: '3.8'
services:
    vault:
      command: sh
      build : 
        context: ../
        dockerfile: vault_demo_setup/Dockerfile
      tty: true
      depends_on: 
        - consul
    benchmark:
      command: ["/bin/bash"]
      build: 
        context: ../benchmarking
        dockerfile: Dockerfile
      tty: true
      depends_on: 
        - consul
    consul:
      image: consul:latest
      hostname: "consul"
      # ports:
      #   - "8400:8400"
      #   - "8500:8500"
      #   - "8600:8600"
      command: "agent -server -bootstrap-expect 2 -ui -disable-host-node-id -client 0.0.0.0"
    consul2:
      image: consul:latest
      hostname: "consul2"
      command: "agent -server -join consul -disable-host-node-id"
      depends_on: 
        - consul
    consul3:
      image: consul:latest
      hostname: "consul3"
      command: "agent -server -join consul -disable-host-node-id"
      depends_on:
        - consul
        # docker run -d -p 9107:9107 prom/consul-exporter --consul.server=172.17.0.1:8500
    # consul4:
    #   image: consul:latest
    #   hostname: "consul4"
    #   command: "agent -join consul -disable-host-node-id"
    #   depends_on:
    #     - consul
    # consul5:
    #   image: consul:latest
    #   hostname: "consul5"
    #   command: "agent -server -join consul -disable-host-node-id"
    #   depends_on:
    #     - consul
    