#vault response encryption and decryption
public_key_path: resources/mykey.pub
private_key_path: resources/mykey.pem
#cas vault authentication
session_api: https://cas:8081/session
certificate: resources/conf/client.crt
session_name: vault
key: resources/conf/client-key.key
#vault config
vault_address: http://127.0.0.1:8200
check_interval: 15