#vault response encryption and decryption
crypto:
    public_key_path: resources/vault-init/mykey.pub
    private_key_path: resources/vault-init/mykey.pem
#cas vault authentication
cas_vault:
    session_name: vault
    session_api: https://cas:8081/session
    key: resources/vault/conf/client-key.key
    certificate: resources/vault/conf/client.crt
#vault config
vault_address: http://127.0.0.1:8200
check_interval: 15
http_encryption_server:
    port: 8083
grpc_encryption_server:
    cert: resources/vault-init/grpc/cert/service.pem
    key: resources/vault-init/grpc/cert/service.key
    client_cert: resources/vault-init/grpc/cert/ca-cert.pem
    port: 8082