#vault response encryption and decryption
crypto:
    public_key_path: /root/go/bin/resources/vault-init/mykey.pub
    private_key_path: /resources/vault-init/mykey.pem
#cas vault authentication
cas:
    session_name: vault
    url: https://cas:8081/session
    key: /root/go/bin/resources/vault/conf/client-key.key
    certificate: /root/go/bin/resources/vault/conf/client.crt
    session_file: /root/go/bin/resources/vault-init/session.yml
    predecessor_hash: 
#vault config
vault_address: http://127.0.0.1:8200
check_interval: 15
http_encryption_server:
    port: 8083
grpc_encryption_server:
    cert: /root/go/bin/resources/vault-init/grpc/cert/service.pem
    key: /root/go/bin/resources/vault-init/grpc/cert/service.key
    client_cert: /root/go/bin/resources/vault-init/grpc/cert/ca-cert.pem
    port: 8082
gpgcrypto:
    public_key_path: /root/go/bin/resources/vault/vault-experiments/keys/public.asc
    private_key_path: /resources/vault-init/private.asc
    pass_phrase: aquickbrownfoxjumpsoverthelazydog