crypto:
    public_key_path: /root/go/bin/resources/vault-init/mykey.pub
    private_key_path: /root/go/bin/resources/vault-init/mykey.pem
#cas vault authentication
cas:
    session_name: vault-init-auto
    export_to_session:
        - vault-init-pki
        - vault-init-dynamicsecret
        - consul-template-nginx
        - consul-template-mongodb
        - consul-template-demo-client
        - consul-template-dynamic-secret
    url: https://cas:8081/session
    key: /root/go/bin/resources/vault-init/conf/client-key.key
    certificate: /root/go/bin/resources/vault-init/conf/client.crt
    session_file: /root/go/bin/resources/vault-init/session.yml
    test_updated_session_file: /root/go/bin/resources/vault-init/test_updated_session.yml
    predecessor_hash_file: /root/go/bin/resources/vault-init/auto_predecessor_hash.yaml
#vault config
vault_address: http://127.0.0.1:8200
check_interval: 15
shares:
    recovery_shares: 1
    recovery_threshold: 1
    secret_shares: 1
    secret_threshold: 1
http_encryption_server:
    port: 8083
grpc_encryption_server:
    cert: /root/go/bin/resources/vault-init/grpc/cert/service.pem
    key: /root/go/bin/resources/vault-init/grpc/cert/service.key
    client_cert: /root/go/bin/resources/vault-init/grpc/cert/ca-cert.pem
    port: 8082
gpgcrypto:
    - public_key_path: /root/go/bin/resources/vault/vault-experiments/keys/public.asc
      private_key_path: /root/go/bin/resources/vault/vault-experiments/keys/private.asc
      pass_phrase: aquickbrownfoxjumpsoverthelazydog
vault_dynamic_secret:
    vault_url: http://127.0.0.1:8200/v1
    plugin_name: mongodb-database-plugin
    allowed_roles: demo-client
    username: jack
    database: admin
    creation_statements: '{ "db": "admin", "roles": [{ "role": "readWrite" }, {"role": "readWrite", "db": "dev"},{"role": "readWrite", "db": "test"}, {"role": "read", "db": "production"}] }'
    default_ttl: 20m
    max_ttl: 60m
    connection_url: "mongodb://@127.0.0.1:27017/admin?ssl=true"
    config_url: /database/config/
    role_url: /database/roles/
    policy_url: /sys/policy/
    policy_file: /root/go/bin/resources/dynamic-secret/credential-policy.hcl
    secret_engine_url: /sys/mounts/database
    credential_url: /database/creds/
    tls_certificate_key: /root/go/bin/resources/consul-template/templates/client.pem
    tls_ca: /root/go/bin/resources/consul-template/templates/client-ca.crt
vault_pki_config:
    mount_point: pki
    name: nginx 
    default_ttl: 20m
    max_ttl: 60m
    root_max_ttl: 180h
    root_common_name: "scone_root_ca"
    key_usage: 
        - digitalSignature
    ext_key_usage:
        - clientAuth
    vault_url: http://127.0.0.1:8200/v1/
    role_url: /roles/
    policy_url: sys/policy/
    secret_engine_url: sys/mounts/
    policy_file: resources/vault-init/pki.hcl
    certificate_common_name: "127.0.0.1"
    certificate_ip_san: "127.0.0.1"
    certificate_ttl: 
    generate_certificate_url: /issue/
    #internal or exported type
    generate_root_url: /root/generate/exported
    set_config_url: /config/urls
    issuing_certificates: /ca
    crl_distribution_points: /crl
    root_ca_cert_location: resources/rootca/
    generated_cert_location: resources/generatedcert/
