#vault response encryption and decryption
crypto:
    public_key_path: resources/vault-init/mykey.pub
    private_key_path: resources/vault-init/mykey.pem
#cas vault authentication
cas:
    session_name: vault-init
    export_to_session:
        - consul-template
        - demo-client
    url: https://127.0.0.1:8081/session
    key: resources/vault-init/conf/client-key.key
    certificate: resources/vault-init/conf/client.crt
    session_file: resources/vault-init/session.yml
    test_updated_session_file: resources/vault-init/test_updated_session.yml
    predecessor_hash_file: resources/vault-init/predecessor_hash.yaml
#vault config
vault_address: http://127.0.0.1:8200
check_interval: 15
shares:
    recovery_shares: 1
    recovery_threshold: 1
    secret_shares: 1
    secret_threshold: 1
http_encryption_server:
    port: 8083
grpc_encryption_server:
    cert: resources/vault-init/grpc/cert/service.pem
    key: resources/vault-init/grpc/cert/service.key
    client_cert: resources/vault-init/grpc/cert/ca-cert.pem
    port: 8082
gpgcrypto:
    - public_key_path: resources/vault/vault-experiments/keys/public.asc
      private_key_path: resources/vault/vault-experiments/keys/private.asc
      pass_phrase: aquickbrownfoxjumpsoverthelazydog
vault_dynamic_secret:
    vault_url: http://127.0.0.1:8200/v1
    plugin_name: mongodb-database-plugin
    allowed_roles: demo-client
    username: myUserAdmin
    database: admin
    creation_statements: '{ "db": "admin", "roles": [{ "role": "readWrite" }, {"role": "readWrite", "db": "dev"},{"role": "readWrite", "db": "test"}, {"role": "read", "db": "production"}] }'
    default_ttl: 2m
    max_ttl: 6m
    connection_url: "mongodb://{{username}}:{{password}}@mongodb:27017/admin"
    config_url: /database/config/
    role_url: /database/roles/
    policy_url: /sys/policy/
    policy_file: /root/go/bin/resources/dynamic-secret/credential-policy.hcl
    secret_engine_url: /sys/mounts/database
    credential_url: /database/creds/
vault_pki_config:
    name: nginx 
    vault_url: http://127.0.0.1:8200/v1
    role_url: /pki/roles/
    policy_url: /sys/policy/
    secret_engine_url: /sys/mounts/pki
    policy_file: resources/vault-init/pki.hcl
    generate_certificate_url: /pki/issue/
    #internal or exported type
    generate_root_url: /pki/root/generate/exported
    set_config_url: /pki/config/urls
    issuing_certificates: /pki/ca
    crl_distribution_points: /pki/crl
    root_ca_cert_location: resources/rootca/