version: "0.2"
name: vault4
    
services:
    - name: dev4
      image_name: sconecuratedimages/www2019:vault-0.10.0-alpine
      mrenclaves: [a57715ffb7f30a2a3dda324e1e23eafa8ff407b47569f2529faf4782161ecbe0]
      command: /opt/scone/lib/glibc-loader /root/go/bin/vault server -dev
      pwd: /
      environment:
        SCONE_MODE: hw
        SCONE_HEAP: 4G
        VAULT_CONFIG_PATH: /resources/vault/config.hcl